#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
module EyeOfNewt
  class Parser < Racc::Parser


  require 'eye_of_newt/ingredient'

  def initialize(tokenizer, ingredient = EyeOfNewt::Ingredient.new)
    @tokenizer = tokenizer
    @ingredient = ingredient
    super()
  end

  def next_token
    @tokenizer.next_token
  end

  def parse
    do_parse
    @ingredient
  end

  def to_unit(u)
    EyeOfNewt::Unit[u]
  end
##### State transition tables begin ###

racc_action_table = [
     9,    10,    20,     9,    14,    16,    18,     9,    11,    21,
    14,     9,    24,    25,     9,    26 ]

racc_action_check = [
     0,     0,    10,     2,     3,     4,     5,     7,     1,    11,
    12,    14,    18,    20,    23,    24 ]

racc_action_pointer = [
    -2,     8,     1,    -1,     1,     3,   nil,     5,   nil,   nil,
    -5,     9,     5,   nil,     9,   nil,   nil,   nil,     6,   nil,
    10,   nil,   nil,    12,    12,   nil,   nil ]

racc_action_default = [
   -19,   -19,   -19,    -4,    -6,    -7,    -9,   -10,   -13,   -14,
   -16,   -19,    -2,    -3,   -19,    -5,   -15,    -8,   -19,   -12,
   -19,    27,    -1,   -11,   -19,   -18,   -17 ]

racc_goto_table = [
    19,    13,     3,    15,    12,     4,     2,     5,    17,     6,
    22,    23,     1,   nil,   nil,   nil,    19 ]

racc_goto_check = [
    11,     4,     3,     6,     3,     5,     2,     7,     8,     9,
     4,    10,     1,   nil,   nil,   nil,    11 ]

racc_goto_pointer = [
   nil,    12,     6,     2,    -2,     5,    -1,     7,     3,     9,
    -3,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     7,     8 ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 9, :_reduce_none,
  2, 9, :_reduce_none,
  2, 9, :_reduce_none,
  1, 9, :_reduce_none,
  2, 10, :_reduce_none,
  1, 10, :_reduce_none,
  1, 13, :_reduce_7,
  2, 13, :_reduce_8,
  1, 13, :_reduce_9,
  1, 11, :_reduce_10,
  2, 12, :_reduce_11,
  2, 18, :_reduce_12,
  1, 18, :_reduce_none,
  1, 19, :_reduce_none,
  1, 14, :_reduce_15,
  1, 15, :_reduce_16,
  3, 16, :_reduce_17,
  3, 17, :_reduce_18 ]

racc_reduce_n = 19

racc_shift_n = 27

racc_token_table = {
  false => 0,
  :error => 1,
  :WORD => 2,
  :NUMBER => 3,
  :UNIT => 4,
  "," => 5,
  "/" => 6,
  "." => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "WORD",
  "NUMBER",
  "UNIT",
  "\",\"",
  "\"/\"",
  "\".\"",
  "$start",
  "ingredient",
  "quantity",
  "ingredient_name",
  "style",
  "amount",
  "unit",
  "number",
  "fraction",
  "decimal",
  "words",
  "word" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

def _reduce_7(val, _values, result)
 @ingredient.quantity = result 
    result
end

def _reduce_8(val, _values, result)
 @ingredient.quantity = val[0] + val[1] 
    result
end

def _reduce_9(val, _values, result)
 @ingredient.quantity = result 
    result
end

def _reduce_10(val, _values, result)
 @ingredient.name = result 
    result
end

def _reduce_11(val, _values, result)
 @ingredient.style = val[1] 
    result
end

def _reduce_12(val, _values, result)
 result = val.join(' ') 
    result
end

# reduce 13 omitted

# reduce 14 omitted

def _reduce_15(val, _values, result)
 @ingredient.unit = to_unit(result) 
    result
end

def _reduce_16(val, _values, result)
 result = val[0].to_i 
    result
end

def _reduce_17(val, _values, result)
 result = val[0].to_f / val[2].to_f 
    result
end

def _reduce_18(val, _values, result)
 result = val.join.to_f 
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module EyeOfNewt
